FROM python:3.12.7-slim

# 设置工作目录
WORKDIR /app

# 安装系统依赖
RUN apt-get update && apt-get install -y \
    ffmpeg \
    gcc \
    python3-dev \
    && rm -rf /var/lib/apt/lists/*

# 复制项目文件
COPY requirements_local.txt .

# 安装Python依赖
RUN pip install --no-cache-dir -r requirements_local.txt

RUN rm requirements_local.txt